import * as Localization from 'expo-localization';
import * as SecureStore from 'expo-secure-store';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { I18nManager, Platform } from 'react-native';

export type SupportedLocale = 'en' | 'ur-Latn';
const localeKey = 'apnatask.locale';

// English and Roman Urdu are both left-to-right. Disable any RTL state left by
// an older preview that offered an Urdu-script interface.
I18nManager.allowRTL(false);
I18nManager.forceRTL(false);

const resources = {
  en: {
    translation: {
      common: { retry: 'Try again', cancel: 'Cancel', continue: 'Continue', offline: 'You are offline' },
      auth: { title: 'Services you can trust', phone: 'Mobile number', email: 'Invited email', otp: 'Verification code', send: 'Send code', verify: 'Verify and continue', hero: 'Get trusted help nearby', copy: 'Enter your Pakistani mobile number. We only use it to secure your account and coordinate selected work.', copyEmail: 'Closed-alpha access uses email at no cost. Only invited test accounts can continue; phone verification returns before public launch.', copyGuest: 'Enter the closed alpha instantly. Phone verification returns before public launch.', guestHint: 'Email confirmation is temporarily off for browser testing. Use sample names, tasks, locations, and images only.', enterAlpha: 'Enter closed alpha', guestUnavailable: 'The test session could not start. Please retry in a moment.', localHint: 'Local preview is ready. Enter any valid Pakistani mobile number to open the seeded provider account; no SMS is sent.', localCode: 'Local preview is ready.', openPreview: 'Open local preview', smsSent: 'Verification code sent by SMS.', emailSent: 'Secure sign-in link sent. Open it in this browser; check spam if it does not arrive.', enterSms: 'Enter the code sent by SMS', enterCode: 'Enter the 6-digit verification code', retry: 'Verification could not start. Try again in a moment.', invalidPhone: 'Enter a valid Pakistani mobile number, for example 0300 1234567.', inviteOnly: 'This email has not been invited to the closed alpha.', rateLimited: 'Too many attempts. Wait a few minutes before requesting another code.', serviceUnavailable: 'SMS verification is temporarily unavailable. Try again shortly.', emailUnavailable: 'Email verification is temporarily unavailable. Try again shortly.', localOffline: 'The local ApnaTask services are not responding. Confirm the API is running, then retry.', unable: 'Unable to verify', phonePlaceholder: '0300 1234567', emailPlaceholder: 'name@example.com', otpLabel: '6-digit verification code', sendFull: 'Send verification code', sendEmail: 'Email secure sign-in link', different: 'Use a different account', terms: 'By continuing, you confirm you are 18 or older and agree to ApnaTask’s Terms and Privacy Policy.' },
      tabs: { home: 'Home', tasks: 'My tasks', messages: 'Messages', account: 'Account', jobs: 'Find jobs', credits: 'Credits' },
      nav: { loadingAccount: 'Loading your account…', checkingProvider: 'Checking provider access…', becomeProvider: 'Become a provider', identity: 'Identity verification', taskOffer: 'Task offer', conversation: 'Conversation', postTask: 'Post a task', taskDetails: 'Task details', support: 'Support' },
      home: { greeting: 'Assalam-o-Alaikum', title: 'What do you need help with?', post: 'Post a task' },
      categories: { plumbing: 'Plumbing', electrical: 'Electrical', cleaning: 'Cleaning', 'ac-repair': 'AC repair', carpentry: 'Carpentry', painting: 'Painting', 'appliance-repair': 'Appliance repair' },
      experience: {
        home: { providerMode: 'Provider mode', title: 'What can we help you fix today?', searchLabel: 'Describe the problem', searchPlaceholder: 'Plumber, bijli, safai…', startTask: 'Start a task with “{{query}}”', kyc: 'KYC reviewed', privateAddress: 'Exact address private', cash: 'Cash after work', supplyTitle: 'Verified help around you', supplyDetail: 'Privacy-safe live supply groups—not individual provider locations.', providers: '{{count}} available verified providers', supplyUnavailable: 'Live supply is temporarily unavailable; you can still post a task.', supplyPrivacy: 'Only groups of three or more available, KYC-approved providers appear.', servicesTitle: 'Popular services', servicesDetail: 'Start with a familiar category or describe the problem above.', loading: 'Loading services…', unavailable: 'Services unavailable', offlineDetail: 'Your saved services may still appear while offline.', quickPost: 'QUICK POST', notSure: 'Not sure which service?', ctaCopy: 'Describe the problem once. Nearby verified providers can respond with private offers.' },
        active: { eyebrow: 'ACTIVE TASK', track: 'Track task', openWork: 'Open assigned work', detail: { pending: 'Safety check in progress', draft: 'Waiting for verification', open: 'Finding relevant nearby providers', accepted: 'A provider has been selected', en_route: 'Provider is on the way', in_progress: 'Work is in progress', completion_requested: 'Completion needs confirmation' } },
        provider: { available: 'Available', paused: 'Paused', live: 'Live opportunities', nearby: 'Nearby work', subtitle: 'New tasks matched to your verified services and area.', availableForWork: 'Available for work', presenceCopy: 'Only matching tasks inside your service area are considered.', availabilityLabel: 'Provider availability', updateLocation: 'Use current service location', updatingLocation: 'Updating location…', locationRequired: 'Location permission is required to show relevant nearby work.', visible: 'You are visible for relevant nearby opportunities.', pausedMessage: 'Availability is paused.', locationFailed: 'Service location could not be updated. Check your connection and retry.', radius: 'SERVICE RADIUS', radiusA11y: '{{count}} kilometre service radius', approvedServices: 'APPROVED SERVICES', all: 'All', allA11y: 'All approved services', map: 'Map', list: 'List', origin: 'Your service location', privacy: 'Pins show approximate localities. Exact customer locations stay private until selection.', away: '{{distance}} km away', viewBid: 'View task & quick bid', finding: 'Finding relevant work…', noFeed: 'No live feed yet', noFeedDetail: 'Confirm your current service location, availability, and approved services.', retryLocation: 'Update location and retry', noMatches: 'No matching tasks right now', noMatchesDetail: 'The map stays active. Try a wider radius or another approved category; declining work never harms a hidden score.', expand: 'Expand to 25 km', refresh: 'Refresh', offers: '{{count}} active offer', offers_plural: '{{count}} active offers', first: 'Be the first provider to respond', limited: 'Open for a limited time', feedUnavailable: 'Feed unavailable', reasons: { proximity: 'Very close to your service location', freshness: 'Recently posted in your category', urgency: 'Customer needs a response soon', budget_signal: 'Budget details are available', fair_exposure: 'Few providers have responded so far', category_fit: 'Matches an approved service on your profile', provider_reliability: 'Your verified work history fits this task', predicted_completion: 'Strong likelihood of a successful completion' } },
        post: { eyebrow: 'POST A TASK', what: 'What happened?', where: 'Where and when?', reviewTitle: 'Review before posting', draftPrivacy: 'Your draft saves automatically. The exact location stays private until you select a provider.', problem: 'Problem', location: 'Location', review: 'Review', service: 'SERVICE', shortTitle: 'Short title', titlePlaceholder: 'Leaking kitchen sink', describe: 'Describe the work', budget: 'Budget in PKR (optional)', showProblem: 'Show the problem', photoStatus: '{{count}}/5 photos · location metadata is removed.', addPhotos: 'Add photos', photosError: 'Photos could not be opened. Check media permission and retry.', continueLocation: 'Continue to location', taskLocation: 'Task location', locationHelp: 'Search across Pakistan or use current location.', currentLocation: 'Use my current location', findAddress: 'Find address', addressPlaceholder: 'Sector, colony, or nearest landmark', searching: 'Searching…', search: 'Search', chooseLocation: 'Choose {{place}}', selectLocation: 'Select this location', moveMap: 'Move the map to position the pin', mapPrivacy: 'The pin is the task location. Only the selected provider receives the exact point.', attribution: 'Map © OpenFreeMap · address data © OpenStreetMap contributors', chosenLocation: 'Chosen task location', resolvingPin: 'Finding address under the pin…', when: 'WHEN DO YOU NEED HELP?', asap: 'As soon as possible', today: 'Today', scheduled: 'Schedule later', flexible: 'Flexible', back: 'Back', reviewTask: 'Review task', safetyTitle: 'Ready for a safety check', safetyCopy: 'Contact details and spam are checked before providers can see it.', selectedService: 'Selected service', openOffers: 'Open to offers', providersPrivacy: 'Providers see only an approximate locality. Your exact pin is revealed only to the provider you select.', postTask: 'Post task', edit: 'Edit', locationPermission: 'Location permission is off. Enable it in settings or search for the address on the map.', pinImprecise: 'Location pinned. Search nearby if the address label is not precise enough.', locationUnavailable: 'Location is unavailable. Check the device permission and try again.', pinNotFound: 'No address was found under that pin. Move it slightly or choose a search result.', waitPin: 'Wait a moment while the address under the pin is confirmed.', required: 'Review the highlighted steps: service, problem details, and a confirmed map location are required.', offlineDraft: 'You are offline. The draft is safe, but posting needs a confirmed connection.', postFailed: 'The task was not posted. Please retry.', problemRequired: 'Choose a service and add a short, clear explanation before continuing.', locationRequired: 'Choose and confirm the task location on the map before reviewing.' },
        job: { open: 'Open task', invalidOffer: 'Enter a clear offer in PKR before sending.', offerFailed: 'Offer not sent. The task may have expired or your credit floor may have been reached.', feedbackFailed: 'Feedback was not saved. Your ability to bid or receive work is not affected; please retry.', feedbackThanks: 'Thank you. This match was flagged for review and will not affect a hidden acceptance score.', loading: 'Loading task…', unavailable: 'Task unavailable', customerBudget: 'CUSTOMER BUDGET', quick: 'Quick offer', quickHint: 'Pick a price and send—one tap after selection.', offerA11y: 'Offer {{amount}}', yourOffer: 'Your offer (PKR)', offerPlaceholder: 'e.g. 2500', arrival: 'ARRIVAL ESTIMATE', arriveIn: 'Arrive in {{time}}', min30: '30 min', hour1: '1 hour', hour2: '2 hours', hour4: '4 hours', note: 'Short note (optional)', notePlaceholder: 'What is included in your offer?', firstCost: 'FIRST OFFER COST', freeLaunch: 'Free during launch', revisionsFree: 'Revisions, counteroffers, and chat are free.', chargeNotice: 'Charging will only start after advance notice; never retroactively.', send: 'Send {{amount}}', offerWord: 'offer', privacy: 'The exact address and customer phone remain private until you are selected.', closeFeedback: 'Close match feedback', irrelevant: 'This match is not relevant', why: 'What made this match irrelevant?', improve: 'This improves dispatch quality. Declining or reporting a match never harms an undisclosed acceptance score.', wrongService: 'Wrong service', tooFar: 'Too far away', timing: 'Timing does not work', unclear: 'Scope is unclear', sendFeedback: 'Send private feedback' },
        task: { loading: 'Loading task…', unavailable: 'Task unavailable', eyebrow: 'YOUR TASK', progress: 'Task progress', current: 'Current status', locality: 'Locality', budget: 'Customer budget', exactAddress: 'Exact address', privateAddress: 'Private until you select a provider', offers: 'Provider offers', offersDetail: 'Private offers from KYC-reviewed providers.', checkingOffers: 'Checking offers…', kyc: 'KYC reviewed', verifiedReviews: '{{count}} verified reviews', newProvider: 'New provider', completedJobs: '{{count}} completed', arrivesMinutes: 'arrives in about {{count}} min', arrivesHours: 'arrives in about {{count}} hr', message: 'Message', select: 'Select provider', noOffers: 'No offers yet', noOffersDetail: 'Verified providers nearby can still submit an offer until this task expires.', workFinished: 'Is the work finished?', confirmCopy: 'Confirm only after checking the work. Payment is cash directly to the provider.', confirm: 'Confirm completion', reviewWork: 'Review completed work', reviewCopy: 'Optional, work-specific feedback helps customers compare verified experience.', overall: 'Overall', punctuality: 'Punctuality', communication: 'Communication', workmanship: 'Workmanship', comment: 'Comment (optional)', publishReview: 'Publish verified-work review', stars: '{{label}} {{count}} stars', selectFailed: 'Could not select provider', selectFailedDetail: 'The task may already have changed. Refresh and retry.', selected: 'Provider selected', codeMessage: 'Your completion code is {{code}}. Only share it after the work is finished.', codeUnavailable: 'Completion code unavailable', supportOverride: 'Contact support for an auditable override.', completionFailed: 'Could not complete task', completionFailedDetail: 'The code was rejected or task status changed.', reviewFailed: 'Review not submitted', thanks: 'Thank you', reviewExisting: 'A review may already exist.', reviewPublished: 'Your verified-work review is published.', status: { draft: 'Draft', pending: 'Checking', open: 'Open', accepted: 'Provider selected', en_route: 'Provider travelling', in_progress: 'Work in progress', completion_requested: 'Awaiting confirmation', completed: 'Completed', expired: 'Expired', cancelled: 'Cancelled', disputed: 'Disputed' }, timeline: { checking: 'Checking task', verified: 'Task verified', notifying: 'Notifying nearby providers', offers: 'Offers received', provider_selected: 'Provider selected', travelling: 'Provider travelling', working: 'Work in progress', confirmation: 'Awaiting confirmation', completed: 'Completed' } },
        chat: { sendFailed: 'Message not sent. Your text is restored—check the connection and retry.', loading: 'Loading conversation…', unavailable: 'Conversation unavailable', private: 'Private conversation · never share an OTP or payment PIN', start: 'Start the conversation', startDetail: 'Ask a question, clarify the work, or agree on what the offer includes.', replyA11y: 'Reply to message: {{message}}', sending: 'Sending…', read: 'Read', delivered: 'Delivered', replying: 'Replying to', cancel: 'Cancel', message: 'Message', placeholder: 'Write a message', send: 'Send message' },
        credits: { loading: 'Loading credits…', unavailable: 'Credits unavailable', title: 'Bid credits', subtitle: 'A clear view of your promotional and purchased credit.', available: 'AVAILABLE CREDIT', promotional: 'PROMOTIONAL', purchased: 'PURCHASED', pricing: 'Bid pricing', paidCopy: '{{fee}} for the first offer on a task. Revisions and chat are free.', freeCopy: 'Bids are currently free. Charging starts only after advance notice and top-ups are operational.', floor: 'Your balance may reach {{floor}} before new bids are paused.', promoExpires: 'Promotional credit expires', purchasedLasts: 'Purchased credit does not' },
        assigned: { loading: 'Loading assigned work…', unavailable: 'Assigned work unavailable', title: 'Your work', subtitle: 'Everything you need for tasks customers selected you for.', statusFailed: 'Status not updated', retry: 'Refresh and retry.', exactAddress: 'Exact address', call: 'Call customer', onWay: 'I am on the way', start: 'Start work', request: 'Request completion', empty: 'No assigned work', emptyDetail: 'When a customer selects your offer, the task and private contact details will appear here.' },
        map: { aria: 'Interactive task map', loading: 'Loading live map…', unavailable: 'Map unavailable', searchWorks: 'Address search still works. Check the configured map style.', marker: 'Task', toggleAttribution: 'Toggle attribution', mapTitle: 'Map', zoomIn: 'Zoom in', zoomOut: 'Zoom out', windowsHelp: 'Use Ctrl + scroll to zoom the map', macHelp: 'Use ⌘ + scroll to zoom the map', mobileHelp: 'Use two fingers to move the map' },
      },
      onboarding: { chooseLanguage: 'Choose your language', languageHelp: 'The whole app will use this language. You can change it later.', promise: 'Verified local help. Your address and offers stay private. Pay cash after the work.', mode: 'ONE ACCOUNT, TWO MODES', welcome: 'Welcome to ApnaTask', intro: 'Hire trusted help now. Apply to offer your own services whenever you are ready.', name: 'Your name', create: 'Create my account', saveError: 'Profile was not saved. Please retry.' },
    },
  },
  ur: {
    translation: {
      common: { retry: 'دوبارہ کوشش کریں', cancel: 'منسوخ', continue: 'جاری رکھیں', offline: 'آپ آف لائن ہیں' },
      auth: { title: 'قابلِ اعتماد خدمات', phone: 'موبائل نمبر', otp: 'تصدیقی کوڈ', send: 'کوڈ بھیجیں', verify: 'تصدیق کریں', hero: 'قابلِ اعتماد مدد، آپ کے گھر کے قریب۔', copy: 'اپنا پاکستانی موبائل نمبر استعمال کریں۔ عام SMS چارجز لاگو ہو سکتے ہیں۔', localHint: 'مقامی پیش منظر: 0300 0000001 اور پھر 123456 استعمال کریں۔', localCode: 'مقامی کوڈ تیار ہے۔ جاری رکھنے کے لیے 123456 لکھیں۔', smsSent: 'تصدیقی کوڈ SMS سے بھیج دیا گیا۔', enterSms: 'SMS سے موصول کوڈ لکھیں', retry: 'دوبارہ کوشش کریں۔', localOffline: 'مقامی تصدیق چل نہیں رہی۔ ApnaTask کی مقامی سروسز شروع کر کے دوبارہ کوشش کریں۔', unable: 'تصدیق نہیں ہو سکی', phonePlaceholder: '0300 1234567', otpLabel: '6 ہندسوں کا تصدیقی کوڈ', sendFull: 'تصدیقی کوڈ بھیجیں', different: 'دوسرا نمبر استعمال کریں', terms: 'جاری رکھ کر آپ تصدیق کرتے ہیں کہ عمر 18 سال یا زیادہ ہے اور ApnaTask کی شرائط اور رازداری پالیسی سے اتفاق کرتے ہیں۔' },
      tabs: { home: 'ہوم', tasks: 'میرے کام', messages: 'پیغامات', account: 'اکاؤنٹ', jobs: 'کام تلاش کریں', credits: 'کریڈٹس' },
      nav: { loadingAccount: 'آپ کا اکاؤنٹ لوڈ ہو رہا ہے…', checkingProvider: 'فراہم کنندہ رسائی چیک ہو رہی ہے…', becomeProvider: 'فراہم کنندہ بنیں', identity: 'شناخت کی تصدیق', taskOffer: 'کام کی آفر', conversation: 'گفتگو', postTask: 'کام پوسٹ کریں', taskDetails: 'کام کی تفصیل', support: 'مدد' },
      home: { greeting: 'السلام علیکم', title: 'آپ کو کس کام میں مدد چاہیے؟', post: 'کام پوسٹ کریں' },
      categories: { plumbing: 'پلمبنگ', electrical: 'بجلی کا کام', cleaning: 'صفائی', 'ac-repair': 'اے سی مرمت', carpentry: 'بڑھئی کا کام', painting: 'رنگ و روغن', 'appliance-repair': 'گھریلو آلات کی مرمت' },
      experience: {
        home: { providerMode: 'سروس فراہم کنندہ موڈ', title: 'آج ہم آپ کے لیے کیا ٹھیک کریں؟', searchLabel: 'مسئلہ بیان کریں', searchPlaceholder: 'پلمبر، بجلی، صفائی…', startTask: '“{{query}}” کے ساتھ کام شروع کریں', kyc: 'شناخت کی جانچ شدہ', privateAddress: 'مکمل پتہ نجی', cash: 'کام کے بعد نقد ادائیگی', supplyTitle: 'آپ کے قریب تصدیق شدہ مدد', supplyDetail: 'نجی اور محفوظ دستیابی کے گروپ—انفرادی فراہم کنندہ کا مقام نہیں۔', providers: '{{count}} دستیاب تصدیق شدہ فراہم کنندگان', supplyUnavailable: 'براہ راست دستیابی عارضی طور پر موجود نہیں؛ آپ پھر بھی کام پوسٹ کر سکتے ہیں۔', supplyPrivacy: 'صرف تین یا زیادہ دستیاب، شناخت شدہ فراہم کنندگان کے گروپ دکھائے جاتے ہیں۔', servicesTitle: 'مقبول خدمات', servicesDetail: 'جانی پہچانی خدمت منتخب کریں یا اوپر مسئلہ بیان کریں۔', loading: 'خدمات لوڈ ہو رہی ہیں…', unavailable: 'خدمات دستیاب نہیں', offlineDetail: 'آف لائن ہونے پر محفوظ خدمات پھر بھی نظر آ سکتی ہیں۔', quickPost: 'فوری پوسٹ', notSure: 'خدمت کا یقین نہیں؟', ctaCopy: 'مسئلہ ایک بار بیان کریں۔ قریب کے تصدیق شدہ فراہم کنندگان نجی آفر بھیج سکتے ہیں۔' },
        provider: { available: 'دستیاب', paused: 'رکا ہوا', live: 'براہ راست مواقع', nearby: 'قریب کے کام', subtitle: 'آپ کی تصدیق شدہ خدمات اور علاقے سے ملتے نئے کام۔', availableForWork: 'کام کے لیے دستیاب', presenceCopy: 'صرف آپ کے خدمت علاقے کے مطابق کام شامل کیے جاتے ہیں۔', availabilityLabel: 'فراہم کنندہ کی دستیابی', updateLocation: 'موجودہ خدمت مقام استعمال کریں', updatingLocation: 'مقام اپ ڈیٹ ہو رہا ہے…', locationRequired: 'قریب کے متعلقہ کام دکھانے کے لیے مقام کی اجازت ضروری ہے۔', visible: 'آپ متعلقہ قریبی مواقع کے لیے نظر آ رہے ہیں۔', pausedMessage: 'دستیابی روک دی گئی ہے۔', locationFailed: 'خدمت کا مقام اپ ڈیٹ نہیں ہوا۔ کنکشن چیک کر کے دوبارہ کوشش کریں۔', radius: 'خدمت کا دائرہ', radiusA11y: '{{count}} کلومیٹر خدمت کا دائرہ', approvedServices: 'منظور شدہ خدمات', all: 'سب', allA11y: 'تمام منظور شدہ خدمات', map: 'نقشہ', list: 'فہرست', origin: 'آپ کا خدمت مقام', privacy: 'پن اندازاً علاقہ دکھاتے ہیں۔ انتخاب تک صارف کا مکمل مقام نجی رہتا ہے۔', away: '{{distance}} کلومیٹر دور', viewBid: 'کام دیکھیں اور فوری آفر دیں', finding: 'متعلقہ کام تلاش ہو رہے ہیں…', noFeed: 'ابھی براہ راست فیڈ نہیں', noFeedDetail: 'اپنا موجودہ خدمت مقام، دستیابی اور منظور شدہ خدمات چیک کریں۔', retryLocation: 'مقام اپ ڈیٹ کر کے دوبارہ کوشش کریں', noMatches: 'ابھی کوئی موزوں کام نہیں', noMatchesDetail: 'نقشہ فعال رہے گا۔ دائرہ بڑھائیں یا دوسری منظور شدہ خدمت آزمائیں؛ کام رد کرنے سے کوئی پوشیدہ اسکور خراب نہیں ہوتا۔', expand: 'دائرہ 25 کلومیٹر کریں', refresh: 'تازہ کریں', offers: '{{count}} فعال آفر', offers_plural: '{{count}} فعال آفرز', first: 'پہلی آفر بھیجیں', limited: 'محدود وقت کے لیے کھلا', feedUnavailable: 'فیڈ دستیاب نہیں', reasons: { proximity: 'آپ کے خدمت مقام کے بہت قریب', freshness: 'آپ کی خدمت میں حال ہی میں پوسٹ ہوا', urgency: 'صارف کو جلد جواب چاہیے', budget_signal: 'بجٹ کی تفصیل موجود ہے', fair_exposure: 'ابھی کم فراہم کنندگان نے جواب دیا ہے', category_fit: 'آپ کی منظور شدہ خدمت سے مطابقت', provider_reliability: 'آپ کا تصدیق شدہ کام کا ریکارڈ موزوں ہے', predicted_completion: 'کامیاب تکمیل کا مضبوط امکان' } },
        post: { eyebrow: 'کام پوسٹ کریں', what: 'کیا مسئلہ ہوا؟', where: 'کہاں اور کب؟', reviewTitle: 'پوسٹ کرنے سے پہلے جائزہ', draftPrivacy: 'آپ کا مسودہ خود محفوظ ہوتا ہے۔ فراہم کنندہ منتخب کرنے تک مکمل مقام نجی رہتا ہے۔', problem: 'مسئلہ', location: 'مقام', review: 'جائزہ', service: 'خدمت', shortTitle: 'مختصر عنوان', titlePlaceholder: 'باورچی خانے کا سنک لیک ہے', describe: 'کام کی تفصیل', budget: 'بجٹ پاکستانی روپے میں (اختیاری)', showProblem: 'مسئلہ دکھائیں', photoStatus: '{{count}}/5 تصاویر · مقام کی معلومات ہٹا دی جاتی ہیں۔', addPhotos: 'تصاویر شامل کریں', photosError: 'تصاویر نہیں کھل سکیں۔ میڈیا اجازت چیک کر کے دوبارہ کوشش کریں۔', continueLocation: 'مقام کی طرف جاری رکھیں', taskLocation: 'کام کا مقام', locationHelp: 'پاکستان بھر میں تلاش کریں یا موجودہ مقام استعمال کریں۔', currentLocation: 'میرا موجودہ مقام استعمال کریں', findAddress: 'پتہ تلاش کریں', addressPlaceholder: 'سیکٹر، کالونی یا قریبی مشہور جگہ', searching: 'تلاش جاری ہے…', search: 'تلاش', chooseLocation: '{{place}} منتخب کریں', selectLocation: 'یہ مقام منتخب کریں', moveMap: 'پن لگانے کے لیے نقشہ حرکت دیں', mapPrivacy: 'پن کام کا مقام ہے۔ صرف منتخب فراہم کنندہ مکمل نقطہ دیکھے گا۔', attribution: 'نقشہ اور پتے کا ڈیٹا © Mapbox © OpenStreetMap', chosenLocation: 'منتخب کام کا مقام', resolvingPin: 'پن کے نیچے پتہ تلاش ہو رہا ہے…', when: 'آپ کو مدد کب چاہیے؟', asap: 'جتنی جلد ممکن ہو', today: 'آج', scheduled: 'بعد کے لیے وقت رکھیں', flexible: 'وقت میں لچک', back: 'واپس', reviewTask: 'کام کا جائزہ', safetyTitle: 'حفاظتی جانچ کے لیے تیار', safetyCopy: 'فراہم کنندگان کو دکھانے سے پہلے رابطہ معلومات اور اسپیم چیک ہوتے ہیں۔', selectedService: 'منتخب خدمت', openOffers: 'آفرز کے لیے کھلا', providersPrivacy: 'فراہم کنندگان صرف اندازاً علاقہ دیکھتے ہیں۔ مکمل پن صرف منتخب فراہم کنندہ کو دکھتا ہے۔', postTask: 'کام پوسٹ کریں', edit: 'تبدیل کریں', locationPermission: 'مقام کی اجازت بند ہے۔ ترتیبات میں فعال کریں یا نقشے پر پتہ تلاش کریں۔', pinImprecise: 'مقام پن ہو گیا۔ اگر پتہ درست نہیں تو قریب تلاش کریں۔', locationUnavailable: 'مقام دستیاب نہیں۔ آلے کی اجازت چیک کر کے دوبارہ کوشش کریں۔', pinNotFound: 'اس پن کے نیچے پتہ نہیں ملا۔ پن تھوڑا حرکت دیں یا تلاش کا نتیجہ منتخب کریں۔', waitPin: 'پن کے نیچے پتے کی تصدیق تک ایک لمحہ انتظار کریں۔', required: 'نمایاں مراحل دیکھیں: خدمت، مسئلے کی تفصیل اور تصدیق شدہ نقشہ مقام ضروری ہیں۔', offlineDraft: 'آپ آف لائن ہیں۔ مسودہ محفوظ ہے مگر پوسٹ کرنے کے لیے کنکشن چاہیے۔', postFailed: 'کام پوسٹ نہیں ہوا۔ دوبارہ کوشش کریں۔', problemRequired: 'جاری رکھنے سے پہلے خدمت منتخب کریں اور مختصر واضح تفصیل شامل کریں۔', locationRequired: 'جائزے سے پہلے نقشے پر کام کا مقام منتخب اور تصدیق کریں۔' },
        job: { open: 'کھلا کام', invalidOffer: 'بھیجنے سے پہلے پاکستانی روپے میں واضح آفر لکھیں۔', offerFailed: 'آفر نہیں بھیجی گئی۔ کام ختم ہو چکا ہو سکتا ہے یا کریڈٹ حد پوری ہو گئی ہے۔', feedbackFailed: 'رائے محفوظ نہیں ہوئی۔ آفر دینے یا کام ملنے کی صلاحیت متاثر نہیں؛ دوبارہ کوشش کریں۔', feedbackThanks: 'شکریہ۔ یہ میچ جائزے کے لیے نشان زد ہے اور کسی پوشیدہ قبولیت اسکور پر اثر نہیں ڈالے گا۔', loading: 'کام لوڈ ہو رہا ہے…', unavailable: 'کام دستیاب نہیں', customerBudget: 'صارف کا بجٹ', quick: 'فوری آفر', quickHint: 'قیمت منتخب کریں اور ایک دباؤ سے بھیجیں۔', offerA11y: '{{amount}} کی آفر', yourOffer: 'آپ کی آفر (روپے)', offerPlaceholder: 'مثلاً 2500', arrival: 'پہنچنے کا اندازہ', arriveIn: '{{time}} میں پہنچیں', min30: '30 منٹ', hour1: '1 گھنٹہ', hour2: '2 گھنٹے', hour4: '4 گھنٹے', note: 'مختصر نوٹ (اختیاری)', notePlaceholder: 'آپ کی آفر میں کیا شامل ہے؟', firstCost: 'پہلی آفر کی قیمت', freeLaunch: 'ابتدا میں مفت', revisionsFree: 'ترمیم، جوابی آفر اور چیٹ مفت ہیں۔', chargeNotice: 'فیس صرف پیشگی اطلاع کے بعد شروع ہوگی؛ پچھلے کام پر کبھی نہیں۔', send: '{{amount}} بھیجیں', offerWord: 'آفر', privacy: 'منتخب ہونے تک مکمل پتہ اور صارف کا فون نجی رہتے ہیں۔', closeFeedback: 'میچ کی رائے بند کریں', irrelevant: 'یہ میچ متعلقہ نہیں', why: 'یہ میچ غیر متعلقہ کیوں تھا؟', improve: 'اس سے تقسیم بہتر ہوتی ہے۔ کام رد یا رپورٹ کرنے سے کوئی پوشیدہ قبولیت اسکور متاثر نہیں ہوتا۔', wrongService: 'غلط خدمت', tooFar: 'بہت دور', timing: 'وقت مناسب نہیں', unclear: 'کام واضح نہیں', sendFeedback: 'نجی رائے بھیجیں' },
        task: { loading: 'کام لوڈ ہو رہا ہے…', unavailable: 'کام دستیاب نہیں', eyebrow: 'آپ کا کام', progress: 'کام کی پیش رفت', current: 'موجودہ حالت', locality: 'علاقہ', budget: 'صارف کا بجٹ', exactAddress: 'مکمل پتہ', privateAddress: 'فراہم کنندہ منتخب کرنے تک نجی', offers: 'فراہم کنندگان کی آفرز', offersDetail: 'شناخت شدہ فراہم کنندگان کی نجی آفرز۔', checkingOffers: 'آفرز چیک ہو رہی ہیں…', kyc: 'شناخت کی جانچ شدہ', verifiedReviews: '{{count}} تصدیق شدہ جائزے', newProvider: 'نیا فراہم کنندہ', completedJobs: '{{count}} مکمل کام', arrivesMinutes: 'تقریباً {{count}} منٹ میں پہنچے گا', arrivesHours: 'تقریباً {{count}} گھنٹے میں پہنچے گا', message: 'پیغام', select: 'فراہم کنندہ منتخب کریں', noOffers: 'ابھی کوئی آفر نہیں', noOffersDetail: 'قریب کے تصدیق شدہ فراہم کنندگان کام ختم ہونے تک آفر بھیج سکتے ہیں۔', workFinished: 'کیا کام مکمل ہے؟', confirmCopy: 'کام چیک کرنے کے بعد ہی تصدیق کریں۔ ادائیگی براہ راست نقد ہے۔', confirm: 'تکمیل کی تصدیق', reviewWork: 'مکمل کام کا جائزہ', reviewCopy: 'اختیاری، کام سے متعلق رائے صارفین کو تصدیق شدہ تجربہ سمجھنے میں مدد دیتی ہے۔', overall: 'مجموعی', punctuality: 'وقت کی پابندی', communication: 'رابطہ', workmanship: 'کام کا معیار', comment: 'تبصرہ (اختیاری)', publishReview: 'تصدیق شدہ کام کا جائزہ شائع کریں', stars: '{{label}} {{count}} ستارے', selectFailed: 'فراہم کنندہ منتخب نہیں ہوا', selectFailedDetail: 'کام پہلے ہی بدل چکا ہو سکتا ہے۔ تازہ کر کے دوبارہ کوشش کریں۔', selected: 'فراہم کنندہ منتخب', codeMessage: 'آپ کا تکمیل کوڈ {{code}} ہے۔ صرف کام مکمل ہونے کے بعد شیئر کریں۔', codeUnavailable: 'تکمیل کوڈ دستیاب نہیں', supportOverride: 'قابلِ جانچ مدد کے لیے سپورٹ سے رابطہ کریں۔', completionFailed: 'کام مکمل نہیں ہو سکا', completionFailedDetail: 'کوڈ مسترد ہوا یا کام کی حالت بدل گئی۔', reviewFailed: 'جائزہ جمع نہیں ہوا', thanks: 'شکریہ', reviewExisting: 'ممکن ہے جائزہ پہلے موجود ہو۔', reviewPublished: 'آپ کا تصدیق شدہ کام کا جائزہ شائع ہو گیا۔', status: { draft: 'مسودہ', pending: 'جانچ جاری', open: 'کھلا', accepted: 'فراہم کنندہ منتخب', en_route: 'فراہم کنندہ راستے میں', in_progress: 'کام جاری', completion_requested: 'تصدیق کا انتظار', completed: 'مکمل', expired: 'مدت ختم', cancelled: 'منسوخ', disputed: 'تنازع' }, timeline: { checking: 'کام کی جانچ', verified: 'کام تصدیق شدہ', notifying: 'قریب کے فراہم کنندگان کو اطلاع', offers: 'آفرز موصول', provider_selected: 'فراہم کنندہ منتخب', travelling: 'فراہم کنندہ راستے میں', working: 'کام جاری', confirmation: 'تصدیق کا انتظار', completed: 'مکمل' } },
        chat: { sendFailed: 'پیغام نہیں بھیجا گیا۔ متن واپس آ گیا ہے—کنکشن چیک کر کے دوبارہ کوشش کریں۔', loading: 'گفتگو لوڈ ہو رہی ہے…', unavailable: 'گفتگو دستیاب نہیں', private: 'نجی گفتگو · OTP یا ادائیگی PIN کبھی شیئر نہ کریں', start: 'گفتگو شروع کریں', startDetail: 'سوال کریں، کام واضح کریں یا آفر میں شامل چیزوں پر اتفاق کریں۔', replyA11y: 'پیغام کا جواب: {{message}}', sending: 'بھیجا جا رہا ہے…', read: 'پڑھا گیا', delivered: 'پہنچ گیا', replying: 'جواب دیا جا رہا ہے', cancel: 'منسوخ', message: 'پیغام', placeholder: 'پیغام لکھیں', send: 'پیغام بھیجیں' },
        credits: { loading: 'کریڈٹس لوڈ ہو رہے ہیں…', unavailable: 'کریڈٹس دستیاب نہیں', title: 'آفر کریڈٹس', subtitle: 'تشہیری اور خریدے گئے کریڈٹ کی واضح تفصیل۔', available: 'دستیاب کریڈٹ', promotional: 'تشہیری', purchased: 'خریدا گیا', pricing: 'آفر کی قیمت', paidCopy: 'کام پر پہلی آفر کے لیے {{fee}}۔ ترمیم اور چیٹ مفت ہیں۔', freeCopy: 'آفرز ابھی مفت ہیں۔ فیس صرف پیشگی اطلاع اور ٹاپ اپ فعال ہونے کے بعد شروع ہوگی۔', floor: 'نئی آفرز رکنے سے پہلے بیلنس {{floor}} تک جا سکتا ہے۔', promoExpires: 'تشہیری کریڈٹ ختم ہوتا ہے', purchasedLasts: 'خریدا گیا کریڈٹ ختم نہیں ہوتا' },
        assigned: { loading: 'منتخب کام لوڈ ہو رہے ہیں…', unavailable: 'منتخب کام دستیاب نہیں', title: 'آپ کے کام', subtitle: 'وہ تمام چیزیں جو صارف کے آپ کو منتخب کرنے کے بعد درکار ہیں۔', statusFailed: 'حالت اپ ڈیٹ نہیں ہوئی', retry: 'تازہ کر کے دوبارہ کوشش کریں۔', exactAddress: 'مکمل پتہ', call: 'صارف کو کال کریں', onWay: 'میں راستے میں ہوں', start: 'کام شروع کریں', request: 'تکمیل کی درخواست', empty: 'کوئی منتخب کام نہیں', emptyDetail: 'صارف آپ کی آفر منتخب کرے تو کام اور نجی رابطہ معلومات یہاں آئیں گی۔' },
        map: { aria: 'کام کا تعاملی نقشہ', loading: 'براہ راست نقشہ لوڈ ہو رہا ہے…', unavailable: 'نقشہ دستیاب نہیں', searchWorks: 'پتہ تلاش کرنا اب بھی کام کرتا ہے۔ نقشہ انداز کی ترتیب چیک کریں۔', marker: 'کام', toggleAttribution: 'نقشہ حوالہ دکھائیں یا چھپائیں', mapTitle: 'نقشہ', zoomIn: 'نقشہ بڑا کریں', zoomOut: 'نقشہ چھوٹا کریں', windowsHelp: 'نقشہ بڑا کرنے کے لیے Ctrl اور اسکرول استعمال کریں', macHelp: 'نقشہ بڑا کرنے کے لیے ⌘ اور اسکرول استعمال کریں', mobileHelp: 'نقشہ حرکت دینے کے لیے دو انگلیاں استعمال کریں' },
      },
      onboarding: { chooseLanguage: 'اپنی زبان منتخب کریں', languageHelp: 'پوری ایپ اسی زبان میں نظر آئے گی۔ آپ بعد میں اسے بدل سکتے ہیں۔', promise: 'تصدیق شدہ مقامی مدد۔ آپ کا پتہ اور آفرز نجی رہیں گے۔ کام کے بعد نقد ادائیگی کریں۔', mode: 'ایک اکاؤنٹ، دو طریقے', welcome: 'اپنا ٹاسک میں خوش آمدید', intro: 'ابھی قابلِ اعتماد مدد حاصل کریں۔ جب چاہیں اپنی خدمات فراہم کرنے کے لیے درخواست دیں۔', name: 'آپ کا نام', create: 'میرا اکاؤنٹ بنائیں', saveError: 'پروفائل محفوظ نہیں ہوا۔ دوبارہ کوشش کریں۔' },
    },
  },
  'ur-Latn': {
    translation: {
      common: { retry: 'Dobara koshish karein', cancel: 'Mansookh', continue: 'Jari rakhein', offline: 'Aap offline hain' },
      auth: { title: 'Bharosemand khidmaat', phone: 'Mobile number', email: 'Invited email', otp: 'Tasdeeqi code', send: 'Code bhejein', verify: 'Tasdeeq karein', hero: 'Qareeb bharosemand madad lein', copy: 'Apna Pakistani mobile number likhein. Hum isay sirf account security aur selected kaam ke rabtay ke liye use karte hain.', copyEmail: 'Closed alpha mein free email access use hota hai. Sirf invited test accounts jari rakh sakte hain; public launch se pehle phone tasdeeq wapas hogi.', copyGuest: 'Closed alpha foran kholein. Public launch se pehle phone tasdeeq wapas hogi.', guestHint: 'Browser testing ke liye email confirmation filhal band hai. Sirf sample naam, task, location aur images use karein.', enterAlpha: 'Closed alpha kholein', guestUnavailable: 'Test session shuru nahi hui. Aik lamhay baad dobara koshish karein.', localHint: 'Local preview tayyar hai. Koi valid Pakistani mobile number likh kar seeded provider account kholein; SMS nahi bheja jata.', localCode: 'Local preview tayyar hai.', openPreview: 'Local preview kholein', smsSent: 'Tasdeeqi code SMS se bhej diya gaya.', emailSent: 'Secure sign-in link email ho gaya. Isi browser mein kholein; na mile to spam check karein.', enterSms: 'SMS se aya code likhein', enterCode: '6-digit tasdeeqi code likhein', retry: 'Tasdeeq shuru nahi hui. Aik lamhay baad dobara koshish karein.', invalidPhone: 'Valid Pakistani mobile number likhein, misal 0300 1234567.', inviteOnly: 'Yeh email closed alpha ke liye invite nahi hui.', rateLimited: 'Bohat zyada koshishain hui hain. Naya code mangne se pehle chand minute rukain.', serviceUnavailable: 'SMS tasdeeq filhal available nahi. Thori dair baad dobara koshish karein.', emailUnavailable: 'Email tasdeeq filhal available nahi. Thori dair baad dobara koshish karein.', localOffline: 'Local ApnaTask services jawab nahi de rahin. API chal rahi ho to dobara koshish karein.', unable: 'Tasdeeq nahi ho saki', phonePlaceholder: '0300 1234567', emailPlaceholder: 'name@example.com', otpLabel: '6-digit tasdeeqi code', sendFull: 'Tasdeeqi code bhejein', sendEmail: 'Secure sign-in link email karein', different: 'Doosra account use karein', terms: 'Jari rakh kar aap tasdeeq karte hain ke umar 18 ya zyada hai aur ApnaTask ki Terms aur Privacy Policy se agree karte hain.' },
      tabs: { home: 'Home', tasks: 'Mere kaam', messages: 'Paighamaat', account: 'Account', jobs: 'Kaam dhoondein', credits: 'Credits' },
      nav: { loadingAccount: 'Aap ka account load ho raha hai…', checkingProvider: 'Provider access check ho rahi hai…', becomeProvider: 'Provider banein', identity: 'Shanakht ki tasdeeq', taskOffer: 'Task offer', conversation: 'Conversation', postTask: 'Kaam post karein', taskDetails: 'Task details', support: 'Madad' },
      home: { greeting: 'Assalam-o-Alaikum', title: 'Aap ko kis kaam mein madad chahiye?', post: 'Kaam post karein' },
      categories: { plumbing: 'Plumbing', electrical: 'Bijli ka kaam', cleaning: 'Safai', 'ac-repair': 'AC marammat', carpentry: 'Barhai ka kaam', painting: 'Rang-o-roghan', 'appliance-repair': 'Gharelu alat ki marammat' },
      experience: {
        home: { providerMode: 'Provider mode', title: 'Aaj hum aap ke liye kya theek karein?', searchLabel: 'Masla batayein', searchPlaceholder: 'Plumber, bijli, safai…', startTask: '“{{query}}” se kaam shuru karein', kyc: 'KYC review shuda', privateAddress: 'Mukammal pata private', cash: 'Kaam ke baad cash', supplyTitle: 'Aap ke qareeb tasdeeq shuda madad', supplyDetail: 'Privacy-safe live supply groups—provider ki alag location nahi.', providers: '{{count}} available verified providers', supplyUnavailable: 'Live supply filhal available nahi; aap phir bhi kaam post kar sakte hain.', supplyPrivacy: 'Sirf teen ya zyada available, KYC-approved providers ke groups dikhte hain.', servicesTitle: 'Mashhoor services', servicesDetail: 'Pehchani service chunein ya upar masla batayein.', loading: 'Services load ho rahi hain…', unavailable: 'Services available nahi', offlineDetail: 'Offline honay par saved services phir bhi nazar aa sakti hain.', quickPost: 'QUICK POST', notSure: 'Service ka yaqeen nahi?', ctaCopy: 'Masla aik baar batayein. Qareeb ke verified providers private offers bhej sakte hain.' },
        active: { eyebrow: 'ACTIVE TASK', track: 'Task track karein', openWork: 'Assigned kaam kholein', detail: { pending: 'Safety check jari hai', draft: 'Tasdeeq ka intezar', open: 'Qareeb ke relevant providers dhoonday ja rahay hain', accepted: 'Provider select ho gaya hai', en_route: 'Provider rastay mein hai', in_progress: 'Kaam jari hai', completion_requested: 'Completion confirmation chahiye' } },
        provider: { available: 'Available', paused: 'Paused', live: 'Live opportunities', nearby: 'Qareeb ke kaam', subtitle: 'Aap ki verified services aur ilaqay se miltay naye kaam.', availableForWork: 'Kaam ke liye available', presenceCopy: 'Sirf aap ke service area ke matching tasks shamil hotay hain.', availabilityLabel: 'Provider availability', updateLocation: 'Maujooda service location use karein', updatingLocation: 'Location update ho rahi hai…', locationRequired: 'Qareeb ke relevant kaam dikhane ke liye location permission zaroori hai.', visible: 'Aap relevant nearby opportunities ke liye visible hain.', pausedMessage: 'Availability pause hai.', locationFailed: 'Service location update nahi hui. Connection check karke dobara koshish karein.', radius: 'SERVICE RADIUS', radiusA11y: '{{count}} kilometre service radius', approvedServices: 'APPROVED SERVICES', all: 'Sab', allA11y: 'Tamam approved services', map: 'Map', list: 'List', origin: 'Aap ki service location', privacy: 'Pins andazan ilaqa dikhate hain. Selection tak customer ki exact location private rehti hai.', away: '{{distance}} km door', viewBid: 'Kaam dekhein aur quick bid dein', finding: 'Relevant kaam dhoonday ja rahay hain…', noFeed: 'Abhi live feed nahi', noFeedDetail: 'Apni current service location, availability aur approved services check karein.', retryLocation: 'Location update karke retry karein', noMatches: 'Abhi matching tasks nahi', noMatchesDetail: 'Map active rahega. Radius barhayein ya doosri approved category dekhein; task decline karne se koi hidden score kharab nahi hota.', expand: '25 km tak barhayein', refresh: 'Refresh', offers: '{{count}} active offer', offers_plural: '{{count}} active offers', first: 'Pehla offer bhejein', limited: 'Mehdood waqt ke liye open', feedUnavailable: 'Feed available nahi', reasons: { proximity: 'Aap ki service location ke bohat qareeb', freshness: 'Aap ki category mein naya post hua', urgency: 'Customer ko jaldi jawab chahiye', budget_signal: 'Budget details available hain', fair_exposure: 'Abhi kam providers ne jawab diya hai', category_fit: 'Aap ki approved service se match', provider_reliability: 'Aap ki verified work history is task ke liye munasib hai', predicted_completion: 'Kamiyab completion ka mazboot imkaan' } },
        post: { eyebrow: 'KAAM POST KAREIN', what: 'Kya masla hua?', where: 'Kahan aur kab?', reviewTitle: 'Post se pehle review', draftPrivacy: 'Aap ka draft khud save hota hai. Provider select karne tak exact location private rehti hai.', problem: 'Masla', location: 'Location', review: 'Review', service: 'SERVICE', shortTitle: 'Mukhtasar title', titlePlaceholder: 'Kitchen sink leak ho raha hai', describe: 'Kaam ki tafseel', budget: 'Budget PKR mein (optional)', showProblem: 'Masla dikhayein', photoStatus: '{{count}}/5 photos · location metadata hata diya jata hai.', addPhotos: 'Photos shamil karein', photosError: 'Photos nahi khul sakin. Media permission check karke dobara koshish karein.', continueLocation: 'Location ki taraf jayein', taskLocation: 'Task location', locationHelp: 'Pakistan bhar mein search karein ya current location use karein.', currentLocation: 'Meri current location use karein', findAddress: 'Pata dhoondein', addressPlaceholder: 'Sector, colony ya qareebi mashhoor jagah', searching: 'Talash jari hai…', search: 'Search', chooseLocation: '{{place}} chunein', selectLocation: 'Yeh location chunein', moveMap: 'Pin lagane ke liye map move karein', mapPrivacy: 'Pin task ki location hai. Sirf selected provider exact point dekhega.', attribution: 'Map © OpenFreeMap · address data © OpenStreetMap contributors', chosenLocation: 'Chuni hui task location', resolvingPin: 'Pin ke neeche pata mil raha hai…', when: 'MADAD KAB CHAHIYE?', asap: 'Jitni jaldi ho sake', today: 'Aaj', scheduled: 'Baad ka waqt rakhein', flexible: 'Waqt flexible hai', back: 'Wapas', reviewTask: 'Task review karein', safetyTitle: 'Safety check ke liye tayyar', safetyCopy: 'Providers ko dikhane se pehle contact details aur spam check hotay hain.', selectedService: 'Selected service', openOffers: 'Offers ke liye open', providersPrivacy: 'Providers sirf andazan ilaqa dekhte hain. Exact pin sirf selected provider ko milta hai.', postTask: 'Kaam post karein', edit: 'Badlein', locationPermission: 'Location permission band hai. Settings mein on karein ya map par pata search karein.', pinImprecise: 'Location pin ho gayi. Agar label theek nahi to qareeb search karein.', locationUnavailable: 'Location available nahi. Device permission check karke dobara koshish karein.', pinNotFound: 'Is pin ke neeche pata nahi mila. Pin thora move karein ya search result chunein.', waitPin: 'Pin ke neeche pata confirm honay tak aik lamha rukain.', required: 'Highlighted steps dekhein: service, problem details aur confirmed map location zaroori hain.', offlineDraft: 'Aap offline hain. Draft safe hai lekin post ke liye connection chahiye.', postFailed: 'Task post nahi hua. Dobara koshish karein.', problemRequired: 'Jari rakhne se pehle service chunein aur choti saaf tafseel dein.', locationRequired: 'Review se pehle map par task location chunein aur confirm karein.' },
        job: { open: 'Open task', invalidOffer: 'Bhejne se pehle PKR mein saaf offer likhein.', offerFailed: 'Offer nahi gaya. Task expire ho sakta hai ya credit floor aa gaya hai.', feedbackFailed: 'Feedback save nahi hua. Bid dene ya kaam milne par asar nahi; dobara koshish karein.', feedbackThanks: 'Shukriya. Yeh match review ke liye flag hai aur kisi hidden acceptance score ko affect nahi karega.', loading: 'Task load ho raha hai…', unavailable: 'Task available nahi', customerBudget: 'CUSTOMER BUDGET', quick: 'Quick offer', quickHint: 'Price chunein aur aik tap se bhejein.', offerA11y: '{{amount}} offer karein', yourOffer: 'Aap ka offer (PKR)', offerPlaceholder: 'misal 2500', arrival: 'ARRIVAL ESTIMATE', arriveIn: '{{time}} mein pohanchein', min30: '30 min', hour1: '1 ghanta', hour2: '2 ghantay', hour4: '4 ghantay', note: 'Chota note (optional)', notePlaceholder: 'Aap ke offer mein kya shamil hai?', firstCost: 'FIRST OFFER COST', freeLaunch: 'Launch mein free', revisionsFree: 'Revisions, counteroffers aur chat free hain.', chargeNotice: 'Fee sirf pehle notice ke baad shuru hogi; purane kaam par kabhi nahi.', send: '{{amount}} bhejein', offerWord: 'offer', privacy: 'Select honay tak exact address aur customer phone private rehte hain.', closeFeedback: 'Match feedback band karein', irrelevant: 'Yeh match relevant nahi', why: 'Yeh match irrelevant kyun tha?', improve: 'Is se dispatch behtar hota hai. Task decline ya report karne se koi hidden acceptance score kharab nahi hota.', wrongService: 'Ghalat service', tooFar: 'Bohat door', timing: 'Waqt theek nahi', unclear: 'Kaam saaf nahi', sendFeedback: 'Private feedback bhejein' },
        task: { loading: 'Task load ho raha hai…', unavailable: 'Task available nahi', eyebrow: 'AAP KA TASK', progress: 'Task progress', current: 'Current status', locality: 'Ilaqa', budget: 'Customer budget', exactAddress: 'Exact address', privateAddress: 'Provider select karne tak private', offers: 'Provider offers', offersDetail: 'KYC-reviewed providers ke private offers.', checkingOffers: 'Offers check ho rahay hain…', kyc: 'KYC reviewed', verifiedReviews: '{{count}} verified reviews', newProvider: 'Naya provider', completedJobs: '{{count}} completed', arrivesMinutes: 'taqreeban {{count}} min mein pohanchega', arrivesHours: 'taqreeban {{count}} ghantay mein pohanchega', message: 'Message', select: 'Provider select karein', noOffers: 'Abhi offers nahi', noOffersDetail: 'Qareeb ke verified providers task expire honay tak offer bhej sakte hain.', workFinished: 'Kya kaam mukammal hai?', confirmCopy: 'Kaam check karne ke baad hi confirm karein. Payment seedha cash hai.', confirm: 'Completion confirm karein', reviewWork: 'Mukammal kaam ka review', reviewCopy: 'Optional work-specific feedback customers ko verified tajurba compare karne mein madad deta hai.', overall: 'Overall', punctuality: 'Waqt ki pabandi', communication: 'Rabta', workmanship: 'Kaam ka mayar', comment: 'Comment (optional)', publishReview: 'Verified-work review publish karein', stars: '{{label}} {{count}} stars', selectFailed: 'Provider select nahi hua', selectFailedDetail: 'Task pehle badal chuka ho sakta hai. Refresh karke retry karein.', selected: 'Provider selected', codeMessage: 'Aap ka completion code {{code}} hai. Sirf kaam mukammal honay ke baad share karein.', codeUnavailable: 'Completion code available nahi', supportOverride: 'Auditable override ke liye support se rabta karein.', completionFailed: 'Task complete nahi hua', completionFailedDetail: 'Code reject hua ya task status badal gaya.', reviewFailed: 'Review submit nahi hua', thanks: 'Shukriya', reviewExisting: 'Review pehle se ho sakta hai.', reviewPublished: 'Aap ka verified-work review publish ho gaya.', status: { draft: 'Draft', pending: 'Checking', open: 'Open', accepted: 'Provider selected', en_route: 'Provider rastay mein', in_progress: 'Kaam jari', completion_requested: 'Confirmation ka intezar', completed: 'Completed', expired: 'Expired', cancelled: 'Cancelled', disputed: 'Disputed' }, timeline: { checking: 'Task check ho raha hai', verified: 'Task verified', notifying: 'Nearby providers ko bataya ja raha hai', offers: 'Offers mil gaye', provider_selected: 'Provider selected', travelling: 'Provider rastay mein', working: 'Kaam jari', confirmation: 'Confirmation ka intezar', completed: 'Completed' } },
        chat: { sendFailed: 'Message nahi gaya. Text wapas aa gaya hai—connection check karke retry karein.', loading: 'Conversation load ho rahi hai…', unavailable: 'Conversation available nahi', private: 'Private conversation · OTP ya payment PIN kabhi share na karein', start: 'Conversation shuru karein', startDetail: 'Sawal karein, kaam clear karein ya offer mein shamil cheezon par agree karein.', replyA11y: 'Message ka jawab: {{message}}', sending: 'Bheja ja raha hai…', read: 'Read', delivered: 'Delivered', replying: 'Jawab de rahe hain', cancel: 'Cancel', message: 'Message', placeholder: 'Message likhein', send: 'Message bhejein' },
        credits: { loading: 'Credits load ho rahay hain…', unavailable: 'Credits available nahi', title: 'Bid credits', subtitle: 'Promotional aur purchased credit ki saaf tafseel.', available: 'AVAILABLE CREDIT', promotional: 'PROMOTIONAL', purchased: 'PURCHASED', pricing: 'Bid pricing', paidCopy: 'Task par pehle offer ke liye {{fee}}. Revisions aur chat free hain.', freeCopy: 'Bids abhi free hain. Fee sirf advance notice aur top-ups operational honay ke baad shuru hogi.', floor: 'Nayi bids pause honay se pehle balance {{floor}} tak ja sakta hai.', promoExpires: 'Promotional credit expire hota hai', purchasedLasts: 'Purchased credit expire nahi hota' },
        assigned: { loading: 'Assigned work load ho raha hai…', unavailable: 'Assigned work available nahi', title: 'Aap ka kaam', subtitle: 'Customer ke aap ko select karne ke baad zaroori tamam cheezen.', statusFailed: 'Status update nahi hua', retry: 'Refresh karke retry karein.', exactAddress: 'Exact address', call: 'Customer ko call karein', onWay: 'Main rastay mein hoon', start: 'Kaam shuru karein', request: 'Completion request karein', empty: 'Assigned work nahi', emptyDetail: 'Customer aap ka offer select kare to task aur private contact details yahan ayengi.' },
        map: { aria: 'Interactive task map', loading: 'Live map load ho raha hai…', unavailable: 'Map available nahi', searchWorks: 'Address search ab bhi kaam karta hai. Configured map style check karein.', marker: 'Task', toggleAttribution: 'Map attribution kholein ya band karein', mapTitle: 'Map', zoomIn: 'Zoom in', zoomOut: 'Zoom out', windowsHelp: 'Map zoom karne ke liye Ctrl + scroll use karein', macHelp: 'Map zoom karne ke liye ⌘ + scroll use karein', mobileHelp: 'Map move karne ke liye do ungliyan use karein' },
      },
      onboarding: { chooseLanguage: 'Apni zubaan chunein', languageHelp: 'Poori app isi zubaan mein nazar aayegi. Aap baad mein badal sakte hain.', promise: 'Tasdeeq shuda local madad. Aap ka pata aur offers private rehte hain. Kaam ke baad cash dein.', mode: 'AIK ACCOUNT, DO MODES', welcome: 'ApnaTask mein khush aamdeed', intro: 'Abhi bharosemand madad lein. Jab tayyar hon apni services dene ke liye apply karein.', name: 'Aap ka naam', create: 'Mera account banayein', saveError: 'Profile save nahi hua. Dobara koshish karein.' },
    },
  },
} as const;

function detectedLocale(): SupportedLocale {
  if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
    const saved = localStorage.getItem(localeKey);
    if (saved === 'ur') {
      localStorage.setItem(localeKey, 'ur-Latn');
      return 'ur-Latn';
    }
    if (saved === 'en' || saved === 'ur-Latn') return saved;
  }
  const languageTag = Localization.getLocales()[0]?.languageTag;
  if (languageTag?.toLowerCase().startsWith('ur-latn')) return 'ur-Latn';
  if (languageTag?.toLowerCase().startsWith('ur')) return 'ur-Latn';
  return 'en';
}

const initialLocale = detectedLocale();

if (Platform.OS === 'web' && typeof document !== 'undefined') {
  document.documentElement.lang = initialLocale;
  document.documentElement.dir = 'ltr';
}

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLocale,
  supportedLngs: ['en', 'ur-Latn'],
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
});

if (Platform.OS !== 'web') {
  void SecureStore.getItemAsync(localeKey).then((saved) => {
    if (saved === 'ur') void setLocale('ur-Latn');
    else if (saved === 'en' || saved === 'ur-Latn') void setLocale(saved);
  });
}

export async function setLocale(locale: SupportedLocale): Promise<boolean> {
  await i18n.changeLanguage(locale);
  if (Platform.OS === 'web' && typeof localStorage !== 'undefined') {
    localStorage.setItem(localeKey, locale);
    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale;
      document.documentElement.dir = 'ltr';
    }
  } else await SecureStore.setItemAsync(localeKey, locale);
  const needsRestart = I18nManager.isRTL;
  I18nManager.allowRTL(false);
  I18nManager.forceRTL(false);
  return needsRestart;
}

export const isRTL = () => false;
export default i18n;
